export { default as CardsBroker } from '@admiral-ds/icons/build/cards/Broker.svg?react';
export { default as CardsIIS } from '@admiral-ds/icons/build/cards/IIS.svg?react';
export { default as CardsPaymentsMaster } from '@admiral-ds/icons/build/cards/PaymentsMaster.svg?react';
export { default as CardsPaymentsMasterEUR } from '@admiral-ds/icons/build/cards/PaymentsMasterEUR.svg?react';
export { default as CardsPaymentsMasterGBR } from '@admiral-ds/icons/build/cards/PaymentsMasterGBR.svg?react';
export { default as CardsPaymentsMasterJPY } from '@admiral-ds/icons/build/cards/PaymentsMasterJPY.svg?react';
export { default as CardsPaymentsMasterRUB } from '@admiral-ds/icons/build/cards/PaymentsMasterRUB.svg?react';
export { default as CardsPaymentsMasterUAH } from '@admiral-ds/icons/build/cards/PaymentsMasterUAH.svg?react';
export { default as CardsPaymentsMasterUSD } from '@admiral-ds/icons/build/cards/PaymentsMasterUSD.svg?react';
